language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
gemfile:
  - ci/Gemfile-rails-3-1
  - ci/Gemfile-rails-3-2
  - ci/Gemfile-rails-4-0
  - ci/Gemfile-rails-4-1
env:
  - DB=sqlite
  - DB=mysql
before_script:
  - "mysql -e 'create database rails_settings_test;' >/dev/null"
before_install: gem update bundler
